In [90]:
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
opimg=Image.fromarray(img)
opimg.show()
#author-@_._hello_world._._



In [101]:
#crop image
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
#remove 30 pixels from all sides
img=img[30:x-30,30:y-30]
opimg=Image.fromarray(img)
opimg.show()
#author-@_._hello_world._._



In [106]:
#negative image
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
img=255-img
opimg=Image.fromarray(img)
opimg.show()
#author-@_._hello_world._._



In [100]:
#seperate R,G,B from images
opimg=[]#to store output images
for i in range(3):
    #copying only one colour to temporary variable 
    #for each iteration and displaying
    temp=np.zeros(img.shape,dtype="uint8")
    temp[:,:,i]=img[:,:,i]
    im=Image.fromarray(temp)
    opimg.append(im)
    opimg[i].show()

#author-@_._hello_world._._



In [28]:
#RGB to greyscale image

opimg=[]#to store output images
for i in range(3):
    grey=img[:,:,i]
    im=Image.fromarray(grey)
    opimg.append(im)
    opimg[i].show()
#author-@_._hello_world._._



In [95]:
#adjust saturation

x,y,z=img.shape
img1=np.copy(img)
s=50
for i in range(x):
    for j in range(y):
        #0,1,2 for R,G,B respectively
        if img[i][j][2]+s<255:
            img1[i][j][2]=img[i][j][2]+s
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._



In [14]:
#adjust brightness

img1=np.copy(img)
x,y,z=img.shape
def bright(img1,b):
    if max(img1[i][j])+b>=255:
        img1[i][j]=255
    else:
        img1[i][j]+=b
def dull(img1,d):
    if min(img1[i][j])-d<=0:
        img1[i][j]=0
    else:
        img1[i][j]-=d

for i in range(x):
    for j in range(y):
        #place either dull or bright function here
        bright(img1,100)
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._



In [82]:
#rotate images 90 degree

inimg=Image.open(r'C:\Users\Home\Pictures\curvedarrow.jpg')
img=np.asarray(inimg)
x,y,z=img.shape

def rotate90():
    global img,img1,y
    img1=np.zeros((y,x,z),dtype='uint8')
    for i in range(y):
        img1[i,:]=img[:,i]
rotate90()
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._

In [68]:
#flip images

inimg=Image.open(r'C:\Users\Home\Pictures\curvedarrow.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
def flip_vertical():
    global img,img1,x
    for i in range(x):
        img1[i,:]=img[x-i-1,:]
def flip_horizontal():
    global img,img1,y
    for i in range(y):
        img1[:,i]=img[:,y-i-1]
flip_vertical()
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._

In [88]:


inimg=Image.open(r'C:\Users\Home\Pictures\curvedarrow.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
def flip_vertical():
    global img,img1,x
    for i in range(x):
        img1[i,:]=img[x-i-1,:]
def flip_horizontal():
    global img,img1,y
    for i in range(y):
        img1[:,i]=img[:,y-i-1]
def rotate90():
    global img,img1,y
    img1=np.zeros((y,x,z),dtype='uint8')
    for i in range(y):
        img1[i,:]=img[:,i] 
def rotate180():
    global img,img1,x,y
    flip_vertical()
    img=img1.copy()
    flip_horizontal()
def rotate270():
    global img,img1,x,y,z
    rotate90()
    img=img1.copy()
    x,y=y,x
    flip_horizontal()
    img=img1.copy()
    flip_vertical()
    
rotate180()
opimg=Image.fromarray(img1)
opimg.show()   

In [125]:
#box blur
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=np.zeros((img.shape),dtype='uint8')
def box_blur(n):
    global img,img1
    for i in range(0,x-n,n):
        for j in range(0,y-n,n):
            img1[i:i+n,j:j+n]+=img[i][j]
box_blur(10)
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._

In [155]:
#smooth blur
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
smooth =  [[1,1,1],
         [1,1,1],
         [1,1,1]]

def blur(kernel):
    global img,img1,x,y,z
    for i in range(x-3):
        for j in range(y-3):
            for k in range(3):
                img1[i][j][k]=(np.sum(img[i:i+3,j:j+3,k]*kernel))//np.sum(kernel)
    img=img1.copy()
for i in range(1):
    blur(smooth)
opimg=Image.fromarray(img1)
opimg.show()
#author-@_._hello_world._._



In [159]:
#with generalized kernel
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
n=20
smooth_blur=np.ones((n,n))

def blur(kernel):
    global img,img1,x,y,z,n
    n=len(kernel)
    for i in range(n,x-n):
        for j in range(n,y-n):
            for k in range(3):
                img1[i][j][k]=(np.sum(img[i:i+n,j:j+n,k]*kernel))//np.sum(kernel)
    
blur(smooth_blur)
opimg=Image.fromarray(img1)
opimg.show()
opimg=Image.fromarray(img)
opimg.show()
#author-@_._hello_world._._


In [161]:
#increase blur efficiency with temp
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\gvr.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
n=20
smooth_blur=np.ones((n,n))
temp=np.ones((x+n*2,y+n*2,3),dtype='uint8')
#copying center
temp[n:x+n,n:y+n]=img[:,:]
#copying corners
temp[:n,:n]=img[:n,:n]
temp[:n,-n:]=img[:n,-n:]
temp[-n:,:n]=img[-n:,:n]
temp[-n:,-n:]=img[-n:,-n:]
#copying edges
temp[:n,n:y+n]=img[:n]
temp[-n:,n:y+n]=img[-n:]
temp[n:x+n,-n:]=img[:,-n:]
temp[n:x+n,:n]=img[:,:n]

temp1=temp.copy()
def blur(kernel):
    global img,img1,x,y,z,n
    n=len(kernel)
    for i in range(n,x+n):
        for j in range(n,y+n):
            for k in range(3):
                temp1[i][j][k]=(np.sum(temp[i:i+n,j:j+n,k]*kernel))//np.sum(kernel)
    img1=temp1[n:x+n,n:y+n]
blur(smooth_blur)
opimg=Image.fromarray(temp)
opimg.show()
opimg=Image.fromarray(temp1)
opimg.show()
#author-@_._hello_world._._


In [ ]:
sharpen=[[0,-0.5,0],[-0.5,3,-0.5],[0,-0.5,0]]

gaussian=[[1,2,1],
        [2,4,2],
        [1,2,1]]

In [108]:
#gaussian kernel
import numpy as np
n=7 #use only odd number
g=np.ones((n,n),dtype='int')

for i in range(1,n):
    #row
    if i<=n//2:
        g[0][i]=g[0][i-1]*2
    else:
        g[0][i]=g[0][i-1]//2
    #coloumn
    if i<=n//2:
        g[i][0]=g[i-1][0]*2
    else:
        g[i][0]=g[i-1][0]//2
    
for i in range(1,n):    
    for j in range(1,n):
        g[i][j]=g[0][j]*g[i][0]
        
print(g)

[[ 1  2  4  8  4  2  1]
 [ 2  4  8 16  8  4  2]
 [ 4  8 16 32 16  8  4]
 [ 8 16 32 64 32 16  8]
 [ 4  8 16 32 16  8  4]
 [ 2  4  8 16  8  4  2]
 [ 1  2  4  8  4  2  1]]


In [162]:
#sharpen kernel
import numpy as np
n=3 #use only odd number
sharpen=np.ones((n,n),dtype='int')
sharpen*=-1
sharpen[n//2][n//2]=n*n

print(sharpen)

[[-1 -1 -1]
 [-1  9 -1]
 [-1 -1 -1]]


In [183]:
#gaussian kernel
import numpy as np
n=7 #use only odd number
g=np.ones((n,n),dtype='float')

for i in range(1,n):
    #row
    if i<=n//2:
        g[0][i]=g[0][i-1]*2
    else:
        g[0][i]=g[0][i-1]//2
    #coloumn
    if i<=n//2:
        g[i][0]=g[i-1][0]*2
    else:
        g[i][0]=g[i-1][0]//2
    
for i in range(1,n):    
    for j in range(1,n):
        g[i][j]=g[0][j]*g[i][0]
t=g[n//2][n//2]
g*=-1/10

g[n//2][n//2]=t
print(g)

[[-0.1 -0.2 -0.4 -0.8 -0.4 -0.2 -0.1]
 [-0.2 -0.4 -0.8 -1.6 -0.8 -0.4 -0.2]
 [-0.4 -0.8 -1.6 -3.2 -1.6 -0.8 -0.4]
 [-0.8 -1.6 -3.2 64.  -3.2 -1.6 -0.8]
 [-0.4 -0.8 -1.6 -3.2 -1.6 -0.8 -0.4]
 [-0.2 -0.4 -0.8 -1.6 -0.8 -0.4 -0.2]
 [-0.1 -0.2 -0.4 -0.8 -0.4 -0.2 -0.1]]


In [182]:
#with generalized kernel
from PIL import Image
import numpy as np
inimg=Image.open(r'C:\Users\Home\Pictures\impy23.jpg')
img=np.asarray(inimg)
x,y,z=img.shape
img1=img.copy()
n=10
smooth_blur=np.ones((n,n))
temp=np.ones((x+n*2,y+n*2,3),dtype='uint8')
#copying center
temp[n:x+n,n:y+n]=img[:,:]
#copying corners
temp[:n,:n]=img[:n,:n]
temp[:n,-n:]=img[:n,-n:]
temp[-n:,:n]=img[-n:,:n]
temp[-n:,-n:]=img[-n:,-n:]
#copying edges
temp[:n,n:y+n]=img[:n]
temp[-n:,n:y+n]=img[-n:]
temp[n:x+n,-n:]=img[:,-n:]
temp[n:x+n,:n]=img[:,:n]

temp1=temp.copy()
def blur(kernel):
    global img,img1,x,y,z,n
    n=len(kernel)
    for i in range(n,x+n):
        print('\r',f' {i-n+1}/{x} th iteration completed',end='',flush=True)
        for j in range(n,y+n):
            for k in range(3):
                temp1[i][j][k]=(np.sum(temp[i:i+n,j:j+n,k]*kernel))/np.sum(kernel)
    img1=temp1[n:x+n,n:y+n]
blur(g)
opimg=Image.fromarray(img1)
opimg.show()
opimg=Image.fromarray(img)
opimg.show()
#author-@_._hello_world._._


  247/247 th iteration completed16/247 th iteration completed 81/247 th iteration completed 191/247 th iteration completed

In [ ]:

sharpen=[[0,-0.5,0],[-0.5,3,-0.5],[0,-0.5,0]]

gaussian=[[1,2,1],
        [2,4,2],
        [1,2,1]]

<h1>create images</h1>


In [2]:
#random pattern greyscale
from PIL import Image
import random
import numpy as np
x,y=200,200
num=np.zeros((x,y),dtype='uint8')
for i in range(x):
    for j in range(y):
        num[i][j]=random.randint(0,255)
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._



In [6]:
#random pattern RGB
from PIL import Image
import random
import numpy as np
x,y=200,200
num=np.zeros((x,y,3),dtype='uint8')
for i in range(x):
    for j in range(y):
        for k in range(3):
            num[i][j][k]=random.randint(0,255)
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._



In [5]:
#greyscale
from PIL import Image
import numpy as np
x,y=100,200
num=np.zeros((x,y),dtype='uint8')
for i in range(x):
    for j in range(y):
        num[i][j]=j
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._



In [9]:
#RGB scale 
from PIL import Image
import numpy as np
x,y=100,200
num=np.zeros((x,y,3),dtype='uint8')
for i in range(x):
    for j in range(y):
        #0,1,2 = r,g,b respectively
        num[i][j][2]=j
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._



In [14]:
#resize scale
#greyscale
from PIL import Image
import numpy as np
d=10 #divisions
x,y=100,200
n=y//d +1
num=np.zeros((x,y),dtype='uint8')
for i in range(0,x-n,n):
    for j in range(0,y-n,n):
        num[i:i+n,j:j+n]=j
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._



In [35]:
#spray colour on sheet
from PIL import Image
import random
import numpy as np
x,y=200,200
sheet_colour=[255,255,255]
num=np.zeros((x,y,3),dtype='int')
num+=sheet_colour
dt=10 #dot_thickness
for i in range(100):
    v=random.randint(0,x-1-dt)
    v1=random.randint(0,y-1-dt)
    num[v:dt,v1:dt,2]=0  #random.randint(0,255)
num=num.astype('uint8')
opimg=Image.fromarray(num)
opimg.show()
#author-@_._hello_world._._

